# Generated by Django 5.2.9 on 2025-12-07 22:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('pais', models.CharField(choices=[('AR', 'Argentina'), ('BO', 'Bolivia'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DO', 'República Dominicana'), ('EC', 'Ecuador'), ('ES', 'España'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('MX', 'México'), ('NI', 'Nicaragua'), ('PA', 'Panamá'), ('PE', 'Perú'), ('PR', 'Puerto Rico'), ('PY', 'Paraguay'), ('SV', 'El Salvador'), ('UY', 'Uruguay'), ('VE', 'Venezuela')], default='CR', max_length=2)),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia / Estado')),
                ('canton', models.CharField(blank=True, max_length=100)),
                ('distrito', models.CharField(blank=True, max_length=100)),
                ('telefono_nacional', models.CharField(help_text='Escribe el número sin código de país ni signos.', max_length=20, verbose_name='Teléfono (sin código de país)')),
                ('notas_estilo', models.TextField(blank=True, help_text='Tallas, colores preferidos u otras notas.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(help_text='Ej: Vestido para boda, laptop de trabajo, regalos…', max_length=200, verbose_name='Título del pedido')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('modo_presupuesto', models.CharField(choices=[('POR_ARTICULO', 'Presupuesto máximo por artículo'), ('TOTAL', 'Presupuesto máximo total')], default='POR_ARTICULO', max_length=20, verbose_name='Modo de presupuesto')),
                ('moneda', models.CharField(choices=[('CRC', 'Colones'), ('USD', 'Dólares')], default='CRC', max_length=3, verbose_name='Moneda')),
                ('presupuesto_maximo_por_articulo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Presupuesto máximo por artículo')),
                ('presupuesto_maximo_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Presupuesto máximo total')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('BUSCANDO_SHOPPER', 'Buscando shopper'), ('EN_SELECCION', 'En selección'), ('COMPRADO', 'Comprado'), ('EN_TRANSITO', 'En tránsito'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='BUSCANDO_SHOPPER', max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='marketplace.customerprofile', verbose_name='Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('monto', models.PositiveIntegerField(verbose_name='Monto')),
                ('tipo_pago', models.CharField(choices=[('ADELANTO', 'Adelanto'), ('PARCIAL', 'Pago parcial'), ('FINAL', 'Pago final')], max_length=20, verbose_name='Tipo de pago')),
                ('metodo', models.CharField(choices=[('SINPE', 'SINPE'), ('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('PAYPAL', 'PayPal'), ('OTRO', 'Otro')], max_length=20, verbose_name='Método de pago')),
                ('nota', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='marketplace.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('pais', models.CharField(choices=[('AR', 'Argentina'), ('BO', 'Bolivia'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DO', 'República Dominicana'), ('EC', 'Ecuador'), ('ES', 'España'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('MX', 'México'), ('NI', 'Nicaragua'), ('PA', 'Panamá'), ('PE', 'Perú'), ('PR', 'Puerto Rico'), ('PY', 'Paraguay'), ('SV', 'El Salvador'), ('UY', 'Uruguay'), ('VE', 'Venezuela')], default='CR', max_length=2)),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia / Estado')),
                ('canton', models.CharField(blank=True, max_length=100)),
                ('distrito', models.CharField(blank=True, max_length=100)),
                ('biografia', models.TextField(blank=True, verbose_name='Biografía')),
                ('especialidades', models.CharField(blank=True, help_text='Ej: moda, tecnología, niños, lujo…', max_length=255)),
                ('ciudad_base', models.CharField(blank=True, max_length=100)),
                ('actualmente_en_el_extranjero', models.BooleanField(default=False)),
                ('ciudad_extranjero', models.CharField(blank=True, max_length=100)),
                ('pais_extranjero', models.CharField(blank=True, max_length=100)),
                ('fecha_regreso', models.DateField(blank=True, null=True)),
                ('tarifa_base_crc', models.PositiveIntegerField(default=0)),
                ('calificacion', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('verificado', models.BooleanField(default=False)),
                ('telefono_nacional', models.CharField(help_text='Número de WhatsApp sin código de país.', max_length=20, verbose_name='Teléfono (sin código de país)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shopper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='marketplace.shopperprofile', verbose_name='Shopper asignado'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(choices=[('PRODUCTO', 'Producto'), ('ENVIO', 'Envío'), ('IMPUESTO', 'Impuesto'), ('VUELO', 'Vuelo'), ('HOSPEDAJE', 'Hospedaje'), ('COMIDA', 'Comida'), ('TRANSPORTE', 'Transporte'), ('OTRO', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('monto', models.PositiveIntegerField(verbose_name='Monto')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('moneda', models.CharField(choices=[('CRC', 'Colones'), ('USD', 'Dólares')], default='CRC', max_length=3, verbose_name='Moneda')),
                ('pedido', models.ForeignKey(blank=True, help_text='Déjalo vacío si es un gasto general (no asociado a un pedido).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='marketplace.order')),
                ('shopper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='marketplace.shopperprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('origen', models.CharField(blank=True, max_length=100)),
                ('ciudad_destino', models.CharField(max_length=100)),
                ('pais_destino', models.CharField(blank=True, max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='marketplace.shopperprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
