# Generated by Django 5.2.9 on 2025-12-07 23:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='foto_referencia_url',
            field=models.URLField(blank=True, verbose_name='Foto de referencia (URL)'),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='foto_url',
            field=models.URLField(default='https://via.placeholder.com/300x300.png?text=Shopper', verbose_name='Foto (URL)'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Artículo')),
                ('categoria', models.CharField(choices=[('ROPA', 'Ropa'), ('CALZADO', 'Calzado'), ('TECH', 'Tecnología'), ('ACCESORIOS', 'Accesorios'), ('COSMETICOS', 'Cosméticos / Belleza'), ('HOGAR', 'Hogar'), ('DEPORTES', 'Deportes'), ('NINOS', 'Niños / Bebés'), ('JUGUETES', 'Juguetes'), ('LUJO', 'Lujo'), ('OTRO', 'Otro')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('nota', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='marketplace.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
