# Generated by Django 5.2.9 on 2025-12-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_order_foto_referencia_url_shopperprofile_foto_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopperprofile',
            name='acepta_nuevos_pedidos',
            field=models.BooleanField(default=True, verbose_name='Acepta nuevos pedidos'),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='acepta_pagos_parciales',
            field=models.BooleanField(default=True, verbose_name='Acepta pagos parciales'),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='monto_maximo_habitual',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Monto máximo habitual (aprox.)'),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='monto_minimo_habitual',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Monto mínimo habitual (aprox.)'),
        ),
        migrations.AlterField(
            model_name='shopperprofile',
            name='especialidades',
            field=models.CharField(blank=True, help_text='Ej: ROPA,TECH,NINOS… (se gestiona desde el formulario)', max_length=255),
        ),
    ]
