# Generated by Django 5.2.9 on 2025-12-08 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_shopperprofile_acepta_nuevos_pedidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopperPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shoppers_fotos/')),
                ('shopper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='marketplace.shopperprofile')),
            ],
        ),
    ]
