# Generated by Django 5.2.9 on 2025-12-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_shopperphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopperprofile',
            name='foto_url',
            field=models.URLField(blank=True, default='https://via.placeholder.com/300x300.png?text=Shopper', null=True, verbose_name='Foto (URL)'),
        ),
    ]
