# Generated by Django 5.2.9 on 2025-12-10 13:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_shopperprofile_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopperprofile',
            name='esquema_tarifas',
            field=models.TextField(blank=True, help_text="Ejemplos: '10% sobre el valor de compra, mínimo 20 USD'; 'tarifa fija por día de compras'; etc.", verbose_name='Esquema de tarifas'),
        ),
        migrations.AlterField(
            model_name='shopperprofile',
            name='foto_url',
            field=models.URLField(default='https://via.placeholder.com/300x300.png?text=Shopper', verbose_name='Foto (URL)'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.customerprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.order')),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.shopperprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
