# Generated by Django 5.2.9 on 2025-12-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_shopperprofile_esquema_tarifas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopperprofile',
            name='pais_extranjero',
            field=models.CharField(blank=True, choices=[('USA', 'U.S.A.')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pais_destino',
            field=models.CharField(blank=True, choices=[('USA', 'U.S.A.')], default='USA', max_length=3),
        ),
    ]
