# Generated by Django 5.2.9 on 2025-12-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_shopperprofile_pais_extranjero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopperprofile',
            name='pais_extranjero',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pais_destino',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
