# Generated by Django 5.2.9 on 2025-12-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_shopperprofile_pais_extranjero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='precio',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Precio final del pedido definido por el shopper.', null=True, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='payment',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='APROBADO', max_length=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='origen',
            field=models.CharField(choices=[('SHOPPER', 'Shopper'), ('CLIENTE', 'Cliente')], default='SHOPPER', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='modo_presupuesto',
            field=models.CharField(choices=[('POR_ARTICULO', 'Presupuesto máximo por artículo'), ('TOTAL', 'Presupuesto máximo total')], default='TOTAL', max_length=20, verbose_name='Modo de presupuesto'),
        ),
    ]
