# Generated by Django 5.2.9 on 2025-12-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_order_precio_payment_estado_payment_origen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='origen',
        ),
        migrations.AddField(
            model_name='payment',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='creado_por',
            field=models.CharField(choices=[('SHOPPER', 'Shopper'), ('CLIENTE', 'Cliente')], default='SHOPPER', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='precio',
            field=models.PositiveIntegerField(blank=True, help_text='Precio acordado del pedido (en la moneda del pedido).', null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='titulo',
            field=models.CharField(blank=True, default='', help_text='Ej: Vestido para boda, laptop de trabajo, regalos…', max_length=200, verbose_name='Título del pedido'),
        ),
    ]
