# Generated by Django 5.2.9 on 2025-12-16 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_remove_payment_estado_remove_payment_origen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='carousel/')),
                ('comentario', models.CharField(blank=True, default='', help_text='Texto corto que se mostrará arriba de la imagen.', max_length=160)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('orden', '-creado'),
            },
        ),
    ]
