# Generated by Django 5.2.9 on 2025-12-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_carouselslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='precio_unitario',
            field=models.PositiveIntegerField(blank=True, help_text='Precio por unidad (en la moneda del pedido).', null=True, verbose_name='Precio unitario'),
        ),
    ]
