# Generated by Django 5.2.9 on 2025-12-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_orderitem_precio_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, help_text='Imagen de fondo para la sección principal del landing.', null=True, upload_to='landing/hero/', verbose_name='Imagen de fondo (Hero)')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
