# Generated by Django 5.2.9 on 2025-12-19 02:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_landinghero'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='hero/')),
                ('activo', models.BooleanField(default=True)),
                ('comentario', models.CharField(blank=True, default='', help_text='Opcional: etiqueta interna para identificar el fondo.', max_length=120)),
            ],
            options={
                'ordering': ('-creado',),
            },
        ),
        migrations.DeleteModel(
            name='LandingHero',
        ),
    ]
