# Generated by Django 5.2.9 on 2025-12-21 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_herobackground_delete_landinghero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopperprofile',
            name='foto_url',
        ),
    ]
