# Generated by Django 5.2.9 on 2025-12-30 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_remove_shopperprofile_foto_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopperprofile',
            name='tarifa_base_crc',
        ),
    ]
