# Generated by Django 5.2.9 on 2026-01-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_remove_shopperprofile_tarifa_base_crc'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='referencia_foto',
            field=models.ImageField(blank=True, help_text='Foto o captura del artículo que el cliente desea.', null=True, upload_to='order_items/', verbose_name='Foto de referencia'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='referencia_url',
            field=models.URLField(blank=True, help_text='URL del producto (ej. Amazon, Walmart, etc.).', verbose_name='Link de referencia'),
        ),
    ]
